/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.gerardo;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author simon
 */
public class Ventana extends javax.swing.JFrame {

    Universidad UAM;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        UAM = new Universidad("UAM", "Manizales", 100);
        
        UAM.agregarEstudiante("Juan", 123, "cra 23", 1, 4, "Ing. Sistemas");
        UAM.agregarEstudiante("Maria", 234, "cra 17", 2, 3, "Ing. Sistemas");
        UAM.agregarEstudiante("Andrea", 354, "cra 11", 3, 5, "Ing. Biomedica");
        UAM.agregarEstudiante("Ernesto", 456, "calle 3", 4, 2, "Ing. Mecanica");
        UAM.agregarEstudiante("Felipe", 567, "cra 30", 5, 2, "Ing. Sistemas");
        UAM.agregarEstudiante("Juana", 678, "cra 7", 6, 4, "Ing. Electronica");
        
        UAM.agregarDepartamento("Ciencias Computacionales","Nano",1);
        UAM.agregarDepartamento("Ciencias Politicas","Colombia",2);
        
        UAM.agregarTrabajador("Oscar",3020,"centro","12/09/08", WIDTH);
        UAM.agregarTrabajador("Simon",3030,"Villa Carmenza","12/09/20", WIDTH);
        UAM.agregarTrabajador("Yani",4020,"Palermo","12/09/14", WIDTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbTituloAddEstudiante = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JTextField();
        btnAddEstudiante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        btnListar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAddMateria = new javax.swing.JButton();
        btnListarWorkers = new javax.swing.JButton();
        btnBuscarWorker = new javax.swing.JButton();
        btnAddWorker = new javax.swing.JButton();
        btnListarDepartments = new javax.swing.JButton();
        btnBuscarDepartments = new javax.swing.JButton();
        btnAddDepartment = new javax.swing.JButton();
        btnListarTeachers = new javax.swing.JButton();
        btnBuscarTeacher = new javax.swing.JButton();
        btnAddTeacher = new javax.swing.JButton();
        btnAddMateriaP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbTitulo.setText("UAM");

        lbTituloAddEstudiante.setText("Agregar estudiante");

        lbNombre.setText("Nombre");

        jLabel1.setText("CI");

        jLabel2.setText("Dirección");

        jLabel3.setText("Código");

        jLabel4.setText("Carrera");

        btnAddEstudiante.setText("Add");
        btnAddEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEstudianteActionPerformed(evt);
            }
        });

        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        jScrollPane1.setViewportView(txtResultados);

        btnListar.setText("Listar Estudiante");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar Estudiante");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAddMateria.setText("Agregar Materia Estudiante");
        btnAddMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMateriaActionPerformed(evt);
            }
        });

        btnListarWorkers.setText("Listar Trabajadores");
        btnListarWorkers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarWorkersActionPerformed(evt);
            }
        });

        btnBuscarWorker.setText("Buscar Trabajador");
        btnBuscarWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarWorkerActionPerformed(evt);
            }
        });

        btnAddWorker.setText("Agregar Trabajador");
        btnAddWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWorkerActionPerformed(evt);
            }
        });

        btnListarDepartments.setText("Listar Departamentos");
        btnListarDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDepartmentsActionPerformed(evt);
            }
        });

        btnBuscarDepartments.setText("Buscar Departamento");
        btnBuscarDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDepartmentsActionPerformed(evt);
            }
        });

        btnAddDepartment.setText("Agregar Departamento");
        btnAddDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDepartmentActionPerformed(evt);
            }
        });

        btnListarTeachers.setText("Listar Profesores");
        btnListarTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarTeachersActionPerformed(evt);
            }
        });

        btnBuscarTeacher.setText("Buscar Profesor");
        btnBuscarTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTeacherActionPerformed(evt);
            }
        });

        btnAddTeacher.setText("Agregar Profesor");
        btnAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeacherActionPerformed(evt);
            }
        });

        btnAddMateriaP.setText("Agregar Materia Profesor");
        btnAddMateriaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMateriaPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(lbTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnListar)
                                .addGap(33, 33, 33)
                                .addComponent(btnBuscar)
                                .addGap(34, 34, 34)
                                .addComponent(btnAddMateria))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnListarDepartments, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnListarWorkers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnListarTeachers))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBuscarTeacher)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAddTeacher)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAddMateriaP))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnBuscarWorker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnBuscarDepartments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAddDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAddWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombre)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCI, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 128, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddEstudiante)
                        .addGap(184, 184, 184))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloAddEstudiante)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addGap(5, 5, 5)
                .addComponent(lbTituloAddEstudiante)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbNombre)
                                .addComponent(btnListar)
                                .addComponent(btnBuscar)
                                .addComponent(btnAddMateria))
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListarWorkers)
                            .addComponent(btnBuscarWorker)
                            .addComponent(btnAddWorker))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(btnListarDepartments)
                                    .addComponent(btnBuscarDepartments)
                                    .addComponent(btnAddDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(btnAddEstudiante)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnListarTeachers)
                            .addComponent(btnBuscarTeacher)
                            .addComponent(btnAddTeacher)
                            .addComponent(btnAddMateriaP)
                            .addComponent(jLabel3)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEstudianteActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText();
        long CI = Long.parseLong(txtCI.getText());
        String direccion = txtDireccion.getText();
        long codigo = Long.parseLong(txtCodigo.getText());
        String carrera = txtCarrera.getText();
        
        UAM.agregarEstudiante(nombre, (int)CI, direccion, codigo, 0, carrera);
        JOptionPane.showMessageDialog(this, "Agregado con éxito");
        txtNombre.setText("");
        txtCI.setText("");
        txtDireccion.setText("");
        txtCodigo.setText("");
        txtCarrera.setText("");
    }//GEN-LAST:event_btnAddEstudianteActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        String resultado = UAM.listarEstudiantes();
        txtResultados.setText(resultado);
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el código a buscar"));
        Estudiante encontrado = UAM.buscarEstudiante(codigo);
        if(encontrado != null){
        txtResultados.setText(encontrado.toString());
        } else{
            JOptionPane.showMessageDialog(this, "No se encontró ningpun estudiante con el código buscado");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAddMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMateriaActionPerformed
          // TODO add your handling code here:
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el código del estudiante"));
        Estudiante aux = UAM.buscarEstudiante(codigo);
        
        AgregarMateria ventanaAux = new AgregarMateria(this, false);
        ventanaAux.setEstudiante(aux);
        ventanaAux.setVisible(true);
    }//GEN-LAST:event_btnAddMateriaActionPerformed

    private void btnListarWorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarWorkersActionPerformed
        // TODO add your handling code here:
        String resultado = UAM.listarTrabajadores();
        txtResultados.setText(resultado);
    }//GEN-LAST:event_btnListarWorkersActionPerformed

    private void btnBuscarWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarWorkerActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog("Ingrese el Nombre del Trabajador a buscar");
        Trabajador encontrado = UAM.buscarTrabajador(nombre);
        if(encontrado != null){
        txtResultados.setText(encontrado.toString());
        } else{
            JOptionPane.showMessageDialog(this, "No se encontró ningpun Trabajador con el nombre buscado");
        }
    }//GEN-LAST:event_btnBuscarWorkerActionPerformed

    private void btnAddWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWorkerActionPerformed
        // TODO add your handling code here:
        AgregarTrabajador ventanaAux = new AgregarTrabajador(this,false);
        ventanaAux.setUAM(UAM);
        ventanaAux.setVisible(true);
        
    }//GEN-LAST:event_btnAddWorkerActionPerformed

    private void btnListarDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDepartmentsActionPerformed
        // TODO add your handling code here:
        String resultado = UAM.listarDepartamentos();
        txtResultados.setText(resultado);
    }//GEN-LAST:event_btnListarDepartmentsActionPerformed

    private void btnBuscarDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDepartmentsActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog("Ingrese el nombre del Departamento a buscar");
        Departamento encontrado = UAM.buscarDepartamento(nombre);
        if(encontrado != null){
        txtResultados.setText(encontrado.toString());
        } else{
            JOptionPane.showMessageDialog(this, "No se encontró ningpun Trabajador con el nombre buscado");
        }
    }//GEN-LAST:event_btnBuscarDepartmentsActionPerformed

    private void btnAddDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDepartmentActionPerformed
        // TODO add your handling code here:
        AgregarDepartamento ventanaAux = new AgregarDepartamento(this,false);
        ventanaAux.setUAM(UAM);
        ventanaAux.setVisible(true);
    }//GEN-LAST:event_btnAddDepartmentActionPerformed

    private void btnListarTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTeachersActionPerformed
        // TODO add your handling code here:
        String nameDepartamento = JOptionPane.showInputDialog("Ingrese el nombre del departamento: ");
        Departamento encontradoDos = UAM.buscarDepartamento(nameDepartamento);
        String resultadoP;
        if(encontradoDos != null){
            resultadoP = encontradoDos.listarProfesores();
            txtResultados.setText(resultadoP);
        }else{
            JOptionPane.showMessageDialog(this, "No se encontró ningpun Departamento con el nombre buscado");
        }
    }//GEN-LAST:event_btnListarTeachersActionPerformed

    private void btnBuscarTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTeacherActionPerformed
        // TODO add your handling code here:
        String nameDepartamento = JOptionPane.showInputDialog("Ingrese el nombre del departamento: ");
        Departamento encontradoDos = UAM.buscarDepartamento(nameDepartamento);
        if(encontradoDos != null){
            String nombre = JOptionPane.showInputDialog("Ingrese el nombre del Profesor a buscar");
            Profesor profesorEncontrado = encontradoDos.buscarProfesor(nombre);
            if(profesorEncontrado != null){
                txtResultados.setText(encontradoDos.buscarProfesor(nombre).toString());
            } else{
                JOptionPane.showMessageDialog(this, "No se encontró ningpun Profesor con el nombre buscado");
            }
        }else{
            JOptionPane.showMessageDialog(this, "No se encontró ningpun Departamento con el nombre buscado");
        }
    }//GEN-LAST:event_btnBuscarTeacherActionPerformed

    private void btnAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeacherActionPerformed
        // TODO add your handling code here:
        String nameDepartamento = JOptionPane.showInputDialog("Ingrese el nombre del departamento: ");
        Departamento encontradoDos = UAM.buscarDepartamento(nameDepartamento);
        if(encontradoDos != null){
            AgregarProfesor ventanaAux = new AgregarProfesor(this,false);
            ventanaAux.setProfesor(encontradoDos);
            ventanaAux.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "No se encontró ningpun Departamento con el nombre buscado");
        }
    }//GEN-LAST:event_btnAddTeacherActionPerformed

    private void btnAddMateriaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMateriaPActionPerformed
        // TODO add your handling code here:
        String nameDepartamento = JOptionPane.showInputDialog("Ingrese el nombre del departamento: ");
        Departamento encontradoDos = UAM.buscarDepartamento(nameDepartamento);
        if(encontradoDos != null){
            String nombre = JOptionPane.showInputDialog("Ingrese el nombre del Profesor: ");
            Profesor profesorAux = encontradoDos.buscarProfesor(nombre);
            AgregarMateriaProfe ventanaAux = new AgregarMateriaProfe(this,false);
            ventanaAux.setProfe(profesorAux);
            ventanaAux.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "No se encontró ningpun Departamento con el nombre buscado");
        }
    }//GEN-LAST:event_btnAddMateriaPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDepartment;
    private javax.swing.JButton btnAddEstudiante;
    private javax.swing.JButton btnAddMateria;
    private javax.swing.JButton btnAddMateriaP;
    private javax.swing.JButton btnAddTeacher;
    private javax.swing.JButton btnAddWorker;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarDepartments;
    private javax.swing.JButton btnBuscarTeacher;
    private javax.swing.JButton btnBuscarWorker;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnListarDepartments;
    private javax.swing.JButton btnListarTeachers;
    private javax.swing.JButton btnListarWorkers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTituloAddEstudiante;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtResultados;
    // End of variables declaration//GEN-END:variables
}
